remove build dir if 'configure' failed in 'mk' command

diff --git a/src/nv-commands/mk b/src/nv-commands/mk
--- a/src/nv-commands/mk
+++ b/src/nv-commands/mk
@@ -114,7 +114,11 @@ plug_install() {
             cd "$subdir"
 
             # compiling
-            ./configure --prefix="$build_path"
+            ./configure --prefix="$build_path" || {
+                echo 'envirius: configure failed!' ;
+                rm -rf "$build_path"
+                exit 1;
+            }
             make --jobs=$(get_cpu_count)
             make install
         fi
