mk: exit cleanly when failing to download the requested package
Now that curl is refusing to download invalid contents, cleanly handle
the case where the uses asked for an invalid version and the server
replied with 404:

$ nv mk my_env --go-prebuilt=invalid
Creating environment: my_env ...
 * installing go-prebuilt==invalid ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
envirius: failed to download 'https://go.googlecode.com/files/goinvalid.linux-amd64.tar.gz'
envirius: unable to fetch source file for go-prebuilt==invalid

diff --git a/src/nv-commands/mk b/src/nv-commands/mk
--- a/src/nv-commands/mk
+++ b/src/nv-commands/mk
@@ -137,9 +137,15 @@ nv_cmd_default() {
 
             # main installation part
             if [ "`nv_is_function 'plug_install'`" = "yes" ]; then
-                plug_install $plugin_name $plugin_ver $env_name_full
+                plug_install $plugin_name $plugin_ver $env_name_full || {
+                    echo "envirius: unable to fetch source file for $plugin_name==$plugin_ver" >&2
+                    exit 1
+                }
             else
-                plug_install_default $plugin_name $plugin_ver $env_name_full
+                plug_install_default $plugin_name $plugin_ver $env_name_full || {
+                    echo "envirius: unable to fetch source file for $plugin_name==$plugin_ver" >&2
+                    exit 1
+                }
             fi
 
             # call post-install actions
@@ -178,6 +184,11 @@ plug_download_default() {
     local tarball_cache="${plugin_name}-${version}.${tarball_ext}"
     local tarball=$(nv_download_file "$tarball_url" "$tarball_cache")
 
+    if [ ! -f "$tarball" ]; then
+        echo "envirius: failed to download '$tarball_url'" >&2
+        return 1
+    fi
+
     echo "$tarball"
 }
 
@@ -210,6 +221,10 @@ plug_install_default() {
                     local tarball=$(plug_download $plugin_name $version)
                 else
                     local tarball=$(plug_download_default $plugin_name $version)
+                fi
+
+                if [ -z "$tarball" ]; then
+                    return 1
                 fi
 
                 # unpacking source file
